---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# WD and packages
```{r}
# To clear your environment 
remove(list = ls())

# To clear your environment 
remove(list = ls())

### set work dir
path <- rstudioapi::getSourceEditorContext()$path
dir  <- dirname(rstudioapi::getSourceEditorContext()$path); dir
setwd(dir)
setwd('..') # set directory by one folder up
getwd()
dir.root <- getwd()


wd <- './data/update_0503_SUM_dist'; wd
getwd()
setwd(wd)
dir.figures <- paste0(dir.root, '/', 'Figures'); dir.figures
dir.output  <- './_output_score';                dir.output




library(readxl)
library(XLConnect)
library(xlsx)
library(tidyverse)
library(scales)


# ################################################################## #
# SDG7 = f(Renewable Energy Use / Total Energy Use)
# ################################################################## #

# df.xlsx <- "0_capital.xlsx"
# df.xlsx <- "6_wat.xlsx";          SDG <- 'SDG6'

# df.xlsx <- "7_ene.xlsx";          SDG <- 'SDG7'
df.xlsx <- "renewable energy transfer network.xlsx";          SDG <- 'SDG7'

# df.xlsx <- "8_mat.xlsx";          SDG <- 'SDG8'
# df.xlsx <- "9_co2.xlsx";          SDG <- 'SDG9'
# df.xlsx <- "12_mat-perCap.xlsx";  SDG <- 'SDG12'
# df.xlsx <- "13_co2-forest.xlsx";  SDG <- 'SDG13'
# df.xlsx <- "15_for.xlsx";         SDG <- 'SDG15'
```



# Data
## Read in from excel
```{r}



# functions 
Net_Import_Cal <- function(df.xlsx) {
  # trade matrix read in R
  s1 = read_excel(df.xlsx, sheet = 1, col_names = T, range = "B1:AP616")
  s2 = matrix
  
  # cal nearby trade matrix
  s3 = s1 * s2
  
  # add country name as a new col
  countries <- colnames(s2[1:41])
  colnames(s3) <- countries; length(countries)
  
  # add year seq to data frame 
  year_seq = rep(seq(1995, 2009, by=1), each = 41)
  s3$year <- year_seq
  
  # total nearby imports
  s4 <- s3 %>% group_by(year) %>% summarise_all(funs(sum))
  
  # tanspose data frame and keep the first col as new header
  s5 = as.data.frame(t(s4[,-1]))
  colnames(s5) <- seq(1995, 2009, by=1)
  s5 <- s5[ order(row.names(s5)), ]
  
  # total nearby exports
  library("reshape2") # expand long table to wide one
  s6 <- s3 %>%
    mutate(row.sum   = rowSums(s3[,1:41]),
           year      = year_seq,
           countries = rep(countries, times = 15)) %>% # times=15, each = 15
    dcast(countries ~ year, value.var = 'row.sum') # year as new col names
  s6 <- data.frame(s6[,-1], row.names=s6[,1])
  s6 <- s6[ order(row.names(s6)), ]
  
  # net nearby imports
  s7 <- s5 - s6
}

# load spatial relation (nearby or distant) matrix
ner_dst_matrix <- "./_input_data/_adjancet_distant_matrix.xlsx"

ner.matrix <- read_excel(path = ner_dst_matrix, sheet = 'S2.country_nearby',  col_names = T, range = "B1:AP616")
dst.matrix <- read_excel(path = ner_dst_matrix, sheet = 'S2.country_distant', col_names = T, range = "B1:AP616")
not.matrix <- read_excel(path = ner_dst_matrix, sheet = 'S2.country_not',     col_names = T, range = "B1:AP616")

# cal net_import under different scenarios using the function we created 
## 1. net_import under only NEARBY trade
matrix <- ner.matrix
s7.ner <- Net_Import_Cal(df.xlsx)

## 2. net_import under only DISTANT trade
matrix <- dst.matrix
s7.dst <- Net_Import_Cal(df.xlsx)

## 3. net_import under NO trade
matrix <- not.matrix
s7.not <- Net_Import_Cal(df.xlsx)
```


## Indicator calculation
### 7.2.1 REU/TEU

```{r}
indicator1 <- 'Indicator 7.2.1'
# ################################################################ #
# local resource-use  --------------------------------------------
# ################################################################ #
## Renewable energy use (reu) data for all countries
dir.up <- dirname(dirname(getwd())); dir.up

re.dir <- paste0(dir.up, "/data/wiod/WIOD-Environmental_Accounts/EU_may12"); re.dir
reu_csv <- paste0(re.dir, '/reu_total_yearly.csv'); reu_csv
reu <- read.csv(reu_csv)[,-c(1,3)] ## remove the 1st and 3rd col, which are not related
reu <- as.data.frame(reu) 
# first col as row name
reu <- data.frame(reu[,-1], row.names = reu[,1])
reu <- reu[ order(row.names(reu)), ]


## Total energy use (EU) data read in
loc <- read_excel(df.xlsx, sheet = 'EU', col_names = T, range = ("A1:P42")) # 'S7.net_import_nearby'
loc <- as.data.frame(loc) 

# first col as row name
loc <- data.frame(loc[,-1], row.names=loc[,1])
loc <- loc[ order(row.names(loc)), ]


### load total energy use (eu) under different scenarios
load('df_eu_scenarios.RData') 
## including: df_rel_eu, df_not_eu, df_ner_eu, df_dst_eu

### For NO-TRADE scenario
### - if no trade, less REU exports, save for local use, more env. friendly
### - if no trade, less total RE exports, save for local use, ... not sure ...
### cal SDG7 = f((REU + Net Exported REU)/ (Total EU - Net Exported EU))
# .....      = f((REU - Net Imported REU)/ (Total EU - Net Exported EU))
df_rel_c <- (reu - 0     )/df_rel_eu
df_not_c <- (reu - s7.not)/df_not_eu
df_ner_c <- (reu - s7.dst)/df_ner_eu
df_dst_c <- (reu - s7.ner)/df_dst_eu

## normalization using the function - Func_norm_sdg_score
## load the function
source(paste0(dir, "/Func_norm_sdg_score_good_bad.R"))

score_c1 <- Func_norm_sdg_score_good(df_rel_c, df_not_c, df_ner_c, df_dst_c,
                                     bottom = 0.025, top = 0.975)
## look at the data distribution
score_c1_long <- score_c1 %>% gather(year, value, 2:16)

ggplot(score_c1_long, aes(x = value)) +
  geom_histogram() +
  facet_wrap(~scenario) +
  theme_bw() +
  ggtitle('Indicator 7.2.1')



# score_c2 <- Func_norm_sdg_score_bad(df_rel_c, df_not_c, df_ner_c, df_dst_c, 
#                                     bottom = 0.025, top = 0.975)
# ## look at the data distribution
# score_c2_long <- score_c2 %>% gather(year, value, ... = 2:16)
# ggplot(score_c2_long, aes(x = value)) + 
#   geom_histogram() + 
#   facet_wrap(~scenario) +
#   theme_bw() +
#   ggtitle('Indicator 7.3.1')

```


### 7.3.1 TEU/GDP
```{r}
indicator2 <- 'Indicator 7.3.1'

### Energy use (1TJ)
df.xlsx <- "7_ene.xlsx"; SDG <- 'SDG7'
loc <- read_excel(df.xlsx, sheet = 'S7.net_import_nearby', 
                  col_names = T, range = ("A1:Q42")) 
loc <- as.data.frame(loc) 
# first col as row name
loc <- data.frame(loc[,-1], row.names=loc[,1])
loc <- loc[ order(row.names(loc)), ]

### GDP data
getwd()
GDP_c_csv  <- './_input_data/_GDP_c_0_capital.csv'
# GDP_b_csv  <- './_input_data/_GDP_b_0_capital.csv'

GDP_c      <- read.csv(file = GDP_c_csv, header = T, stringsAsFactors = F)

GDP_c_rel <- GDP_c %>% filter(scenario == 'rel_c') %>% dplyr::select(-1, -17)
GDP_c_not <- GDP_c %>% filter(scenario == 'not_c') %>% dplyr::select(-1, -17)
GDP_c_ner <- GDP_c %>% filter(scenario == 'ner_c') %>% dplyr::select(-1, -17)
GDP_c_dst <- GDP_c %>% filter(scenario == 'dst_c') %>% dplyr::select(-1, -17)


# ####################################################################### #
# 1) close approach -------------------------------------------------------
# ####################################################################### #

df_rel_eu <- (loc[, -16] + 0     )
df_not_eu <- (loc[, -16] + s7.not)
df_ner_eu <- (loc[, -16] + s7.dst)
df_dst_eu <- (loc[, -16] + s7.ner)

# Save and restore multiple R objects: 
getwd()
# save(df_rel_eu, df_not_eu, df_ner_eu, df_dst_eu, file = 'df_eu_scenarios.RData') 
# load('df_eu_scenarios.RData')

# Cal TEU/GDP
df_rel_c <- (loc[, -16] + 0     )/GDP_c_rel
df_not_c <- (loc[, -16] + s7.not)/GDP_c_not
df_ner_c <- (loc[, -16] + s7.dst)/GDP_c_ner
df_dst_c <- (loc[, -16] + s7.ner)/GDP_c_dst


## normalization using the function - Func_norm_sdg_score
## load the function
source(paste0(dir, "/Func_norm_sdg_score_good_bad.R"))

score_c2 <- Func_norm_sdg_score_bad(df_rel_c, df_not_c, df_ner_c, df_dst_c,
                                    bottom = 0.025, top = 0.975)

## look at the data distribution
score_c2_long <- score_c2 %>% gather(year, value, 2:16)
ggplot(score_c2_long, aes(x = value)) +
  geom_histogram() +
  facet_wrap(~scenario) +
  theme_bw() +
  ggtitle('Indicator 7.3.1')


# score_c1 <- Func_norm_sdg_score_good(df_rel_c, df_not_c, df_ner_c, df_dst_c, 
#                                      bottom = 0.025, top = 0.975)
# ## look at the data distribution
# score_c1_long <- score_c1 %>% gather(year, value, ... = 2:16)
# 
# ggplot(score_c1_long, aes(x = value)) + 
#   geom_histogram() + 
#   facet_wrap(~scenario) +
#   theme_bw() +
#   ggtitle('Indicator 7.2.1')

```


### Comapre two indicators
```{r}

score_c1_long_rel <- score_c1 %>% filter(scenario=='rel_c') %>%
  dplyr::mutate(MeanScore = rowMeans(select(., `1995`:`2009`))) %>%
  # arrange(rev(MeanScore)) %>%
  dplyr::mutate(colorID = rank(MeanScore)) %>%
  gather(year, value, 2:16) %>%
  dplyr::mutate(id = row_number())

score_c2_long_rel <- score_c2 %>% filter(scenario=='rel_c') %>%
  dplyr::mutate(MeanScore = rowMeans(select(., `1995`:`2009`))) %>%
  dplyr::mutate(colorID = rank(MeanScore)) %>%
  gather(year, value, 2:16)%>%
  dplyr::mutate(id = row_number())


# str(score_c1_long_rel)
# ggplot(score_c2_long_rel, aes(x = reorder(nation, colorID), y = value, color =as.factor(colorID))) + 
#   # geom_point() + 
#   geom_boxplot() +
#   theme_bw() +
#   # ggtitle('Indicator 15.2.1') +
#   coord_flip() +
#   theme(legend.position="none")

### plot these 2 indicators in one
score_c12_long_rel <- merge(x = score_c1_long_rel, y = score_c2_long_rel, by = 'id') %>%
  gather(indicator, value, c(value.x, value.y))


unique(score_c12_long_rel$indicator)

label_names <- c(`value.x` = indicator1, `value.y` = indicator2)


### plot - choose the one with greater varance as ordered plot
# ggplot(score_c12_long_rel, 
#        aes(x = reorder(nation.x, colorID.x), 
#            y = value, 
#            color = as.factor(colorID.x))) + 
ggplot(score_c12_long_rel, 
       aes(x = reorder(nation.y, colorID.y), 
           y = value, 
           color = as.factor(colorID.y))) + 
  # geom_point() + 
  geom_boxplot() +
  theme_bw() +
  # ggtitle('SDG 15') +
  ylab('SDG score') +
  xlab('Country') +
  coord_flip() +
  facet_wrap(~indicator, 
             # scales = 'free_x', 
             labeller = as_labeller(label_names))+
  theme(legend.position="none")

getwd()
fname <- paste0(dir.figures, '/compare_2_indicators_', SDG, '-2020.png'); fname
ggsave(filename = fname,  plot = last_plot(), width = 12, height = 6, units = "in", dpi = 500)

```



# Save results
## Goal level (2019) - see code *cal_raw_data_tele_7ene_20190802.Rmd*
## Target level (2020) 
```{r}
# SDG_score_c <- data.frame(score_c1[,1],                          ### country names
#                           (score_c1[,2:16] + score_c2[,2:16])/2, ### mean value
#                           score_c1[,17:18]) %>%                  ### scenario and group info
#   as.data.frame()
# names(SDG_score_c) <- c('nation', seq(1995, 2009), "scenario", "group")
# 
# # save as csv for cal SDGc
# getwd()
# out.dir <- './_output_score'
# fname <- paste0(out.dir, '/score_c_', gsub('.xlsx', '', df.xlsx), '.csv'); fname
# write.csv(x = SDG_score_c, file = fname, row.names = T)

############################################################################################## #
### change on 2020-05-12
### save data at target level
############################################################################################## #
sdg72 <- paste0(out.dir, '/score_c_72_ene.csv'); sdg72
sdg73 <- paste0(out.dir, '/score_c_73_ene.csv'); sdg73
write.csv(x = score_c1, file = sdg72, row.names = T)
write.csv(x = score_c2, file = sdg73, row.names = T)

```



### Diff between dst and ner; by global/ group

```{r}

source(paste0(dir, "/single_diff_func_c_approach.R"))
source(paste0(dir, "/single_diff_func_b_approach.R"))
 
## some fake name for the function to name files
df.xlsx <- "72_ene.xlsx"; SDG <- 'SDG72'
single_diff_func_c(score_c1)

df.xlsx <- "73_ene.xlsx"; SDG <- 'SDG73'
single_diff_func_c(score_c2)

```



### Data_Descriptive_Stats

#### data
```{r}
library(tidyverse)
library(reshape2) # expand long table to wide one
library(scales) # to access break formatting functions

df.xlsx <- "7_ene.xlsx"; SDG <- 'SDG7'

s1 <- read_excel(df.xlsx, sheet = 1, col_names = T, range = "B1:AP616")

names(s1)
s3 = s1

min(as.matrix(s1)); 
colSums(as.matrix(s1) == 0)
max(as.matrix(s1))

# add country name as a new col
countries <- colnames(s1[1:41])
colnames(s3) <- countries; length(countries)

# add year seq to data frame 
year_seq = rep(seq(1995, 2009, by=1), each = 41); #year_seq
s3$year <- year_seq

### total imports
s4 <- s3 %>% group_by(year) %>% summarise_all(funs(sum))
s5 <- as.data.frame(t(s4[,-1])) ## tanspose data frame and keep the first col as new header
colnames(s5) <- seq(1995, 2009, by=1)
s5 <- s5[ order(row.names(s5)), ]

### total  exports
s6 <- s3 %>%
  mutate(row.sum   = rowSums(s3[,1:41]),
         year      = year_seq,
         countries = rep(countries, times = 15)) %>% # times=15, each = 15
  dcast(countries ~ year, value.var = 'row.sum')    # year as new col names
s6 <- data.frame(s6[,-1], row.names=s6[,1])
s6.1 <- s6[ order(row.names(s6)), ]


### input data for plot
ip <- s4[-1] %>% gather(key = 'nation', value = 'value') ## wide to long
ep <- as.data.frame(t(s6)) %>% gather(key = 'nation', value = 'value')

str(ip)

ip.mean <- ip %>% group_by(nation) %>% dplyr::summarise(mean = mean(value))
ip.new  <- merge(x = ip, y = ip.mean, by = 'nation', all.x = T)

ip_ep <- rbind(
  cbind(trade = 'imports', ip),
  cbind(trade = 'exports', ep)
)
ip_ep.new  <- merge(x = ip_ep, y = ip.mean, by = 'nation', all.x = T)
str(ip_ep.new)
```


#### plot

```{r}
lab <- bquote('Virtual total energy use (1TJ)')

ggplot(data = ip_ep.new, aes(x = reorder(nation, mean), y = value, color = trade)) + ## log10(value)
  # geom_point() + 
  geom_boxplot() +
  # scale_y_log10() + 
  theme_bw() +
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = scales::trans_format("log10", scales::math_format(expr = 10^.x))
                ) +
  
  # ggtitle('Indicator 15.2.1') +
  # coord_flip() +
  # theme(legend.position="none") +
  # scale_color_hue(direction = -1) +
  # scale_colour_brewer(direction = -1)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.3)) +
  theme(legend.position = c(0.8, 0.2)) +
  ylab(lab) +
  xlab('Country')

fname <- paste0(dir.figures, '/_Data_Descriptive_Stats_', SDG, '-2020.png'); fname
ggsave(filename = fname, plot = last_plot(), width = 7, height = 5.5, units = "in", dpi = 500)

```




# ################################# #
# The end
# ################################# #
```{r eval=FALSE, include=FALSE}
# ####################################################################### #
# Normalization -----------------------------------------------------------
# ####################################################################### #
# find min and max for further normalization
all_c <- as.data.frame(rbind(df_rel_c, df_not_c, df_ner_c, df_dst_c))
str(all_c)

library(ggplot2)
library(tidyr)
all_c.val <- gather(data = all_c, key = cols, value = value)
ggplot(all_c.val, aes(x = value)) + geom_histogram(bins = 50)

quantile(all_c.val$value, probs = c(0.05, 0.95))
val.min <- quantile(all_c.val$value, probs = 0.05); val.min
val.max <- quantile(all_c.val$value, probs = 0.95); val.max

all_c.val <- all_c.val %>% filter(value >= val.min & value <= val.max)
ggplot(all_c.val, aes(x = value)) + geom_histogram(bins = 50)


#----- normalization use old data numbers ----- #
# max <- read_excel(df.xlsx, sheet = 10, col_names = F, range = "B44") 
# min <- read_excel(df.xlsx, sheet = 10, col_names = F, range = "B45") 
# max <- (data.matrix(max))[1]; max
# min <- (data.matrix(min))[1]; min
#----- ---------------------------------------- #

min <- val.min; min
max <- val.max; max

### if (Energy Use/GDP)
# norm <- function(x){
#   ifelse(x > max, 0, 
#          ifelse(x>min, (x-max)/(min-max)*100, 100))
# }


### A function for normalization 
### if (Renewable Energy/Energy Use)
norm <- function(x){
  ifelse(x < min, 0,
         ifelse(x<max, (x-min)/(max-min)*100, 100))
}


df_rel_c.norm <- df_rel_c
df_not_c.norm <- df_not_c
df_ner_c.norm <- df_ner_c
df_dst_c.norm <- df_dst_c

## apply the function we created
df_rel_c.norm[] <- lapply(df_rel_c.norm, norm)
df_not_c.norm[] <- lapply(df_not_c.norm, norm)
df_ner_c.norm[] <- lapply(df_ner_c.norm, norm)
df_dst_c.norm[] <- lapply(df_dst_c.norm, norm)


## add 'country group code' - i.e., developed or developing
getwd()
group.file <- './_input_data/_nearby_distant_developed_developing_20181110.xlsx'
group.code <- read_excel(group.file, sheet = 'group', col_names = T, range = "A1:B42")
group.code <- arrange(group.code, nation)

## A Function to add nation names to the dataframe
Add_Nation <- function(f){
  df_norm          <- f %>% as.data.frame() %>% mutate(nation   = rownames(df_rel_c))
  df_norm$scenario <- paste0(substr(deparse(substitute(f)), 4, 8))
  df_norm_nation   <- merge(x = df_norm, y = group.code, by.x = 'nation', by.y = 'nation')
  # write to csv
  # out.dir <- './_output_score'
  # fname <- paste0(out.dir, '/score_', substr(deparse(substitute(f)), 4, 8), '.csv')
  # # deparse(substitute(f)), covert dataframe name f to string 'f'
  # print(fname)
  # write.csv(x = df_norm_nation, file = fname, row.names = T)
}

## apply the function we created
score_c_rel <- Add_Nation(df_rel_c.norm)
score_c_not <- Add_Nation(df_not_c.norm)
score_c_ner <- Add_Nation(df_ner_c.norm)
score_c_dst <- Add_Nation(df_dst_c.norm)

## row bind all the results
score_c     <- rbind(score_c_rel, score_c_not, score_c_ner, score_c_dst)
names(score_c)
names(score_c) <- c('nation', seq(1995, 2009), "scenario", "group") # rename the cols

## save as csv
# df.xlsx <- "6_wat.xlsx"
out.dir <- './_output_score'
fname <- paste0(out.dir, '/score_c_', gsub('.xlsx', '', df.xlsx), '.csv'); fname
# write.csv(x = score_c, file = fname, row.names = T)

  

# ####################################################################### #
# 2) baseline approach --------------------------------------------------
# ####################################################################### #

# rep.row  <-function(x,n){matrix(rep(x,each=n),nrow=n)}
# rep.col  <-function(x,n){matrix(rep(x,each=n), ncol=n, byrow=TRUE)}
# loc_base <- as.data.frame(rep.col(loc[,1], 15)) # set the start year 1995 as base line
# 
# 
# # ~~~~~~~~~~ change #5 ~~~~~~~~~~ ----------------------------------------- 
# df_rel_b <- (loc[, -16] + 0     )/GDP_b_rel; colnames(df_rel_b) <- colnames(df_rel_c)
# df_not_b <- (loc_base   + s7.not)/GDP_b_not; colnames(df_not_b) <- colnames(df_rel_c)
# df_ner_b <- (loc_base   + s7.dst)/GDP_b_ner; colnames(df_ner_b) <- colnames(df_rel_c)
# df_dst_b <- (loc_base   + s7.ner)/GDP_b_dst; colnames(df_dst_b) <- colnames(df_rel_c)
# 
# 
# all_b     <- as.data.frame(rbind(df_rel_b, df_not_b, df_ner_b, df_dst_b))
# all_b.val <- gather(all_b, cols, value)
# min <- quantile(all_b.val$value, probs = 0.05); min
# max <- quantile(all_b.val$value, probs = 0.95); max
# 
# df_rel_b.norm <- df_rel_b
# df_not_b.norm <- df_not_b
# df_ner_b.norm <- df_ner_b
# df_dst_b.norm <- df_dst_b
# 
# df_rel_b.norm[] <- lapply(df_rel_b.norm, norm)
# df_not_b.norm[] <- lapply(df_not_b.norm, norm)
# df_ner_b.norm[] <- lapply(df_ner_b.norm, norm)
# df_dst_b.norm[] <- lapply(df_dst_b.norm, norm)
# 
# score_b_rel <- Add_Nation(df_rel_b.norm)
# score_b_not <- Add_Nation(df_not_b.norm)
# score_b_ner <- Add_Nation(df_ner_b.norm)
# score_b_dst <- Add_Nation(df_dst_b.norm)
# 
# # big table
# score_b     <- rbind(score_b_rel, score_b_not, score_b_ner, score_b_dst)
# 
# names(score_b)
# names(score_b) <- c('nation', seq(1995, 2009), "scenario", "group")
# 
# # save csv
# # df.xlsx <- "6_wat.xlsx"
# out.dir <- './_output_score'
# fname <- paste0(out.dir, '/score_b_', gsub('.xlsx', '', df.xlsx), '.csv'); fname
# write.csv(x = score_b, file = fname, row.names = T)







# ####################################################################### #
# 3) baseline approach 2 --------------------------------------------------
# ####################################################################### #

# rep.row  <-function(x,n){matrix(rep(x,each=n),nrow=n)}
# rep.col  <-function(x,n){matrix(rep(x,each=n), ncol=n, byrow=TRUE)}
# 
# s7.not.base <- as.data.frame(rep.col(s7.not[,1], 15)) # set the start year 1995 as base line
# s7.dst.base <- as.data.frame(rep.col(s7.dst[,1], 15))
# s7.ner.base <- as.data.frame(rep.col(s7.ner[,1], 15))
# 
# 
# df_rel_b <- (loc[, -16] +      0     )/GDP_b_rel; colnames(df_rel_b) <- colnames(df_rel_c)
# df_not_b <- (loc[, -16] + s7.not.base)/GDP_b_not; colnames(df_not_b) <- colnames(df_rel_c)
# df_ner_b <- (loc[, -16] + s7.dst.base)/GDP_b_ner; colnames(df_ner_b) <- colnames(df_rel_c)
# df_dst_b <- (loc[, -16] + s7.ner.base)/GDP_b_dst; colnames(df_dst_b) <- colnames(df_rel_c)
# 
# 
# all_b     <- as.data.frame(rbind(df_rel_b, df_not_b, df_ner_b, df_dst_b))
# all_b.val <- gather(all_b, cols, value)
# min <- quantile(all_b.val$value, probs = 0.05); min
# max <- quantile(all_b.val$value, probs = 0.95); max
# 
# df_rel_b.norm <- df_rel_b
# df_not_b.norm <- df_not_b
# df_ner_b.norm <- df_ner_b
# df_dst_b.norm <- df_dst_b
# 
# df_rel_b.norm[] <- lapply(df_rel_b.norm, norm)
# df_not_b.norm[] <- lapply(df_not_b.norm, norm)
# df_ner_b.norm[] <- lapply(df_ner_b.norm, norm)
# df_dst_b.norm[] <- lapply(df_dst_b.norm, norm)
# 
# score_b_rel <- Add_Nation(df_rel_b.norm)
# score_b_not <- Add_Nation(df_not_b.norm)
# score_b_ner <- Add_Nation(df_ner_b.norm)
# score_b_dst <- Add_Nation(df_dst_b.norm)
# 
# # big table
# score_b2     <- rbind(score_b_rel, score_b_not, score_b_ner, score_b_dst)
# 
# names(score_b2)
# names(score_b2) <- c('nation', seq(1995, 2009), "scenario", "group")
# 
# # save csv
# # df.xlsx <- "6_wat.xlsx"
# out.dir <- './_output_score'
# fname <- paste0(out.dir, '/score_b2_', gsub('.xlsx', '', df.xlsx), '.csv'); fname
# write.csv(x = score_b2, file = fname, row.names = T)




# ########################################################################### #
# diff between dst and ner; by global/ group
# ########################################################################### #

# source("G:/My Drive/_paper/170923_trade_Global SDGs/results/single_diff_func_c_approach.R")
# source("G:/My Drive/_paper/170923_trade_Global SDGs/results/single_diff_func_b_approach.R")

# single_diff_func_c(score_c)
# single_diff_func_b(score_b)

```

